name: Release ankra-cli

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux-windows:
    name: Build Linux and Windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build binary
        run: |
          mkdir -p dist
          if [ "${{ matrix.goos }}" = "windows" ]; then
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/ankra-cli-${{ matrix.goos }}-${{ matrix.goarch }}.exe
          else
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/ankra-cli-${{ matrix.goos }}-${{ matrix.goarch }}
          fi
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/ankra-cli-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build and Sign macOS
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
          - goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=${{ matrix.goarch }} go build -o dist/ankra-cli-darwin-${{ matrix.goarch }}
      - name: Import Code-Signing Certificates
        if: ${{ secrets.APPLE_CERTIFICATE_BASE64 != '' }}
        uses: Apple-Actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      - name: Sign macOS binary
        if: ${{ secrets.APPLE_CERTIFICATE_BASE64 != '' }}
        run: |
          codesign --force --options runtime --sign "${{ secrets.APPLE_SIGNING_IDENTITY }}" dist/ankra-cli-darwin-${{ matrix.goarch }}
      - name: Notarize macOS binary
        if: ${{ secrets.APPLE_CERTIFICATE_BASE64 != '' }}
        run: |
          zip -j dist/ankra-cli-darwin-${{ matrix.goarch }}.zip dist/ankra-cli-darwin-${{ matrix.goarch }}
          xcrun notarytool submit dist/ankra-cli-darwin-${{ matrix.goarch }}.zip \
            --apple-id "${{ secrets.APPLE_ID }}" \
            --password "${{ secrets.APPLE_APP_PASSWORD }}" \
            --team-id "${{ secrets.APPLE_TEAM_ID }}" \
            --wait
          rm dist/ankra-cli-darwin-${{ matrix.goarch }}.zip
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/ankra-cli-darwin-${{ matrix.goarch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
