apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluent-bit
data:
    fluent-bit.conf: |-
        [SERVICE]
            Flush        1
            Log_Level    info
            Daemon       Off
            Parsers_File parsers.conf
    
        [INPUT]
            Name         tail
            Path         /var/log/containers/*.log
            Parser       docker
            Tag          kube.*
            Refresh_Interval 5
    
        [OUTPUT]
            Name         stdout
            Match        *
