apiVersion: v1
kind: ImportCluster
metadata:
  name: test-this-cluster-i
  description: Importing my Kubernetes cluster
spec:
  git_repository:
    provider: github
    credential_name: User-Myothas
    repository: Myothas/test-github-repo
    branch: main
  stacks:
    - name: logging
      description: Stack for logging
      manifests:
        - name: namespace-fluent-bit
          parents: [ ]
          from_file: "manifests/fluent-bit-namespace.yaml"

        - name: configmap-fluent-bit
          parents:
            - manifest: namespace-fluent-bit
          from_file: "manifests/fluent-bit-configmap.yaml"


      addons:
        - name: fluent-mark
          chart_name: fluent-bit
          chart_version: 0.49.1
          repository_url: https://fluent.github.io/helm-charts
          namespace: fluent-bit
          parents:
            - manifest: configmap-fluent-bit
          configuration_type: standalone
          configuration:
            values: |-
              fluent-bit:
                service:
                  enabled: true
                input:
                  tail:
                    enabled: true
