package client

// Every /api/v1 path the CLI builds must be a route the cluster binary
// registers.
//
// The client composes its requests from string literals
// (`c.BaseURL + "/api/v1/org/ai-agent-runs/" + runID`, and more often
// `fmt.Sprintf("%s/api/v1/org/credentials/%s", c.BaseURL, id)`), so nothing
// types a path against anything and a renamed or removed route on the
// cluster side is a 404 for every user of that command. The scan therefore
// takes an /api/v1 path from anywhere in a literal, not just from its start:
// the Sprintf form puts the base URL first, and anchoring at the start saw
// only 89 of the 295 paths the module actually builds.
//
// routes.json is the cluster repo's
// route census, generated by walking the real chi router (ankraio/cluster,
// docs/route-census.md), and it is the truth this test checks against. CI
// downloads it and points ANKRA_CLUSTER_ROUTES_JSON at it; locally:
//
//	ANKRA_CLUSTER_ROUTES_JSON=../cluster/routes.json go test ./internal/client/ -run ClusterRoutes
//
// Matching is path-only and shape-aware: a route's `{param}` segment accepts
// any call segment and a trailing `*` on a route matches the rest, but a
// dynamic call segment (a `%s` placeholder or an appended identifier) is
// accepted only by a route parameter, never by a literal, because the real
// request would 404 there. No census route ends in a bare "/" (chi allows
// it, the cluster router does not use it), so normalising a trailing slash
// to a parameter cannot mask a literal route. A literal that ends in "/" is a prefix the code
// appends an identifier to (`prefix + id + "/tailscale"`); the scan sees only
// the literal, so it is checked as `prefix/{}*`: the route must carry a
// parameter where the identifier goes, and whatever the code appends after
// it is not seen and not checked. A `%s`, `%d`, `%v`, `%q` or `%x`
// placeholder is one dynamic segment. Matching is path-only: the census
// lists methods, but the client chooses its method at the http.NewRequest
// call, not in the literal, so a method check needs the call site walked
// too; that is the next refinement, not this one.
// cluster_routes_allowlist.json beside this file is a ratchet (this repo
// gitignores testdata/): the paths, with the file but never the line, that
// did not resolve when the check was introduced. A new one fails, a
// listed one that resolves fails too, so the list only shrinks. Regenerate
// it deliberately with ANKRA_CLUSTER_ROUTES_UPDATE=1.
//
// What is on it today is two different things, and only one of them is safe:
//
//   - A `%s` that holds a literal segment chosen at run time, not an
//     identifier: the provider kind in `/api/v1/clusters/%s/%s` (hetzner,
//     digitalocean, ...) and the relay sub-path in
//     `/api/v1/clusters/%s/kubernetes/%s`. The census registers those
//     segments literally, the strict rule accepts a dynamic call segment
//     only where a route has a parameter, and the literal scan cannot see
//     which value the variable holds. Unverifiable here, not a defect.
//   - `/api/v1/org/clusters/imported/{}/power-schedules`, which the cluster
//     genuinely does not register: importedapi mounts power schedules only
//     on the session surface (`/org/...`), with no `/api/v1/org` bearer
//     twin, so `ankra cluster power-schedules` 404s. Tracked as
//     ankra-htxvm.15; it comes off this list when the route exists on the
//     cluster side, not before.
//   - The three `/api/v1/org/clusters/imported/{}/security/...` Trivy
//     integration paths (`trivy/history`, `report-schedule`,
//     `report-schedule/send-now`) that `ankra security history` and
//     `ankra security report-schedule` build: their bearer twins ship in
//     cluster#2789 (ankra-1lzs5.4) and were not on main when the commands
//     landed. Once that PR merges they resolve, this test fails on them as
//     listed-but-resolving, and the fix is one ANKRA_CLUSTER_ROUTES_UPDATE=1
//     run that drops them.

import (
	"encoding/json"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"
)

type clusterRouteCensus struct {
	Routes []struct {
		Method  string `json:"method"`
		Path    string `json:"path"`
		Package string `json:"package"`
	} `json:"routes"`
}

// A brace placeholder or any fmt verb the client uses for a path segment.
var clusterRouteParameter = regexp.MustCompile(`\{[^}]*\}|%(?:\[\d+\])?[sdvqx]`)

// An /api/v1 path anywhere inside a string literal, running to the first
// character a path cannot hold. Most of the client builds its URLs as
// fmt.Sprintf("%s/api/v1/...", c.BaseURL, ...), so a scan anchored at the
// start of the literal would collect only the minority that begins with the
// path and would report full coverage over the rest.
var clusterAPIPath = regexp.MustCompile(`/api/v1/[A-Za-z0-9_.\-/{}%\[\]?&=:~*]*`)

// normalizeClusterPath collapses every parameter to `{}`, turns a trailing
// slash into the appended-identifier tail `{}*`, and ignores a query string.
func normalizeClusterPath(path string) string {
	withoutQuery := strings.SplitN(path, "?", 2)[0]
	tail := ""
	if strings.HasSuffix(withoutQuery, "/") && len(withoutQuery) > 1 {
		withoutQuery = strings.TrimSuffix(withoutQuery, "/")
		tail = "/{}*"
	}
	collapsed := clusterRouteParameter.ReplaceAllString(withoutQuery, "{}")
	segments := strings.Split(collapsed, "/")
	for index, segment := range segments {
		if strings.Contains(segment, "{}") {
			segments[index] = "{}"
		}
	}
	return strings.Join(segments, "/") + tail
}

// clusterPathMatches reports whether a normalized call path has the shape of a
// normalized route pattern: a route parameter accepts anything, a dynamic call
// segment is accepted only by a route parameter, and the appended-identifier
// tail `{}*` is accepted by a route parameter with anything after it.
func clusterPathMatches(callPath string, routePath string) bool {
	call := strings.Split(callPath, "/")
	route := strings.Split(routePath, "/")
	for index, routeSegment := range route {
		if routeSegment == "*" {
			return true
		}
		if index >= len(call) {
			return false
		}
		callSegment := call[index]
		if callSegment == "{}*" {
			return routeSegment == "{}"
		}
		if routeSegment == "{}" || routeSegment == callSegment {
			continue
		}
		return false
	}
	return len(call) == len(route)
}

// clusterPathLiterals returns every /api/v1 path held by a string literal in
// the module's non-test Go files, with the file and line it was found in. A
// literal may carry the path anywhere in it, and more than one.
func clusterPathLiterals(t *testing.T, moduleRoot string) map[string][]string {
	t.Helper()
	found := map[string][]string{}
	fileSet := token.NewFileSet()
	walkError := filepath.WalkDir(moduleRoot, func(path string, entry os.DirEntry, walkError error) error {
		if walkError != nil {
			return walkError
		}
		if entry.IsDir() {
			if entry.Name() == ".git" || entry.Name() == "node_modules" || strings.HasPrefix(entry.Name(), ".") && path != moduleRoot {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			return nil
		}
		file, parseError := parser.ParseFile(fileSet, path, nil, 0)
		if parseError != nil {
			return parseError
		}
		relative, _ := filepath.Rel(moduleRoot, path)
		ast.Inspect(file, func(node ast.Node) bool {
			literal, isLiteral := node.(*ast.BasicLit)
			if !isLiteral || literal.Kind != token.STRING {
				return true
			}
			value, unquoteError := strconv.Unquote(literal.Value)
			if unquoteError != nil {
				return true
			}
			where := relative + ":" + strconv.Itoa(fileSet.Position(literal.Pos()).Line)
			for _, match := range clusterAPIPath.FindAllString(value, -1) {
				// Prose in a help string ends the sentence, not the path.
				path := strings.TrimRight(match, ".,")
				found[path] = append(found[path], where)
			}
			return true
		})
		return nil
	})
	if walkError != nil {
		t.Fatalf("scanning %s: %v", moduleRoot, walkError)
	}
	return found
}

// TestClusterRoutesAreRegistered checks every /api/v1 literal in the module
// against the cluster route census.
func TestClusterRoutesAreRegistered(t *testing.T) {
	censusPath := os.Getenv("ANKRA_CLUSTER_ROUTES_JSON")
	if censusPath == "" {
		// Skipping locally keeps `go test ./...` green for someone who has
		// not fetched the census. Skipping in CI would be the bug this whole
		// test exists to prevent, one level up: a pipeline that lost its
		// fetch step would report "passed" for a check that never ran.
		if os.Getenv("CI") != "" {
			t.Fatal("ANKRA_CLUSTER_ROUTES_JSON is unset under CI: the workflow fetches the cluster route census before this step, so an unset value means that step is gone or failed, and skipping here would report a check that never ran as passed")
		}
		t.Skip("ANKRA_CLUSTER_ROUTES_JSON is unset: point it at the cluster repo's routes.json to check the CLI's paths against the route census (CI does)")
	}
	raw, readError := os.ReadFile(censusPath)
	if readError != nil {
		t.Fatalf("reading the route census at %s: %v", censusPath, readError)
	}
	var census clusterRouteCensus
	if unmarshalError := json.Unmarshal(raw, &census); unmarshalError != nil {
		t.Fatalf("%s is not a route census: %v", censusPath, unmarshalError)
	}
	if len(census.Routes) == 0 {
		t.Fatalf("%s lists no routes", censusPath)
	}
	registered := map[string]bool{}
	for _, route := range census.Routes {
		registered[normalizeClusterPath(route.Path)] = true
	}
	var routeIndex []string
	for path := range registered {
		routeIndex = append(routeIndex, path)
	}

	literals := clusterPathLiterals(t, filepath.Join("..", ".."))
	var resolved, unresolved []string
	for value, locations := range literals {
		callPath := normalizeClusterPath(value)
		isRegistered := false
		for _, routePath := range routeIndex {
			if clusterPathMatches(callPath, routePath) {
				isRegistered = true
				break
			}
		}
		// The entry carries the file but not the line, so an edit above the
		// literal does not turn a known gap into a new one.
		sort.Strings(locations)
		entry := value + "  (" + strings.SplitN(locations[0], ":", 2)[0] + ")"
		if isRegistered {
			resolved = append(resolved, entry)
		} else {
			unresolved = append(unresolved, entry)
		}
	}
	sort.Strings(resolved)
	sort.Strings(unresolved)
	t.Logf("cluster routes: %d distinct /api/v1 literals checked against %d registered routes; %d resolved, %d unresolved",
		len(literals), len(census.Routes), len(resolved), len(unresolved))

	allowlistPath := "cluster_routes_allowlist.json"
	switch os.Getenv("ANKRA_CLUSTER_ROUTES_UPDATE") {
	case "", "0", "1":
	default:
		t.Fatalf("ANKRA_CLUSTER_ROUTES_UPDATE=%q is not a value this test understands; use 1 to regenerate or leave it unset to compare", os.Getenv("ANKRA_CLUSTER_ROUTES_UPDATE"))
	}
	if os.Getenv("ANKRA_CLUSTER_ROUTES_UPDATE") == "1" {
		encoded, marshalError := json.MarshalIndent(unresolved, "", "  ")
		if marshalError != nil {
			t.Fatalf("encoding the allowlist: %v", marshalError)
		}
		if writeError := os.WriteFile(allowlistPath, append(encoded, '\n'), 0o644); writeError != nil {
			t.Fatalf("writing %s: %v", allowlistPath, writeError)
		}
		return
	}
	var allowlist []string
	allowRaw, allowReadError := os.ReadFile(allowlistPath)
	if allowReadError != nil {
		t.Fatalf("reading %s: %v (run once with ANKRA_CLUSTER_ROUTES_UPDATE=1 to create it)", allowlistPath, allowReadError)
	}
	if unmarshalError := json.Unmarshal(allowRaw, &allowlist); unmarshalError != nil {
		t.Fatalf("%s is not a JSON list of strings: %v", allowlistPath, unmarshalError)
	}
	allowed := map[string]bool{}
	for _, entry := range allowlist {
		allowed[entry] = true
	}
	current := map[string]bool{}
	for _, entry := range unresolved {
		current[entry] = true
	}
	var appeared, gone []string
	for _, entry := range unresolved {
		if !allowed[entry] {
			appeared = append(appeared, entry)
		}
	}
	for _, entry := range allowlist {
		if !current[entry] {
			gone = append(gone, entry)
		}
	}
	if len(appeared) > 0 {
		t.Errorf("%d /api/v1 path(s) the cluster router does not register (fix the path, add the route on the cluster side, or record it deliberately with ANKRA_CLUSTER_ROUTES_UPDATE=1):\n  %s",
			len(appeared), strings.Join(appeared, "\n  "))
	}
	if len(gone) > 0 {
		t.Errorf("%d allowlisted path(s) now resolve or moved; drop them so the list keeps shrinking (ANKRA_CLUSTER_ROUTES_UPDATE=1 rewrites it):\n  %s",
			len(gone), strings.Join(gone, "\n  "))
	}
}

// TestClusterAPIPathExtraction pins what the scan lifts out of a literal:
// the path wherever it starts, every one when a literal holds several, and
// no trailing prose from a help string.
func TestClusterAPIPathExtraction(t *testing.T) {
	cases := map[string][]string{
		`/api/v1/org/credentials`:                    {"/api/v1/org/credentials"},
		`%s/api/v1/org/credentials/%s`:               {"/api/v1/org/credentials/%s"},
		`https://platform.ankra.app/api/v1/mcp`:      {"/api/v1/mcp"},
		"`GET %s/api/v1/org/ai-agent-runs` -- lists": {"/api/v1/org/ai-agent-runs"},
		`see /api/v1/org/security.`:                  {"/api/v1/org/security"},
		`%s/api/v1/a/%s and %s/api/v1/b`:             {"/api/v1/a/%s", "/api/v1/b"},
		`no path here`:                               nil,
	}
	for input, want := range cases {
		var got []string
		for _, match := range clusterAPIPath.FindAllString(input, -1) {
			got = append(got, strings.TrimRight(match, ".,"))
		}
		if strings.Join(got, "|") != strings.Join(want, "|") {
			t.Errorf("paths in %q = %v, want %v", input, got, want)
		}
	}
}

// TestNormalizeClusterPath pins the shapes the matcher relies on.
func TestNormalizeClusterPath(t *testing.T) {
	cases := map[string]string{
		"/api/v1/org/ai-agent-runs/":                 "/api/v1/org/ai-agent-runs/{}*",
		"/api/v1/clusters/%s/nodes/%s/restart":       "/api/v1/clusters/{}/nodes/{}/restart",
		"/api/v1/org/runs/{run_id}/stream?follow=1":  "/api/v1/org/runs/{}/stream",
		"/api/v1/clusters/{cluster_id}/k8s/*":        "/api/v1/clusters/{}/k8s/*",
		"/api/v1/org/stack-profiles/import-draft":    "/api/v1/org/stack-profiles/import-draft",
		"/api/v1/org/credentials/morpheus/ssh-key%s": "/api/v1/org/credentials/morpheus/{}",
	}
	for input, want := range cases {
		if got := normalizeClusterPath(input); got != want {
			t.Errorf("normalizeClusterPath(%q) = %q, want %q", input, got, want)
		}
	}
	route := normalizeClusterPath
	if !clusterPathMatches("/api/v1/org/ai-agent-runs/{}*", route("/api/v1/org/ai-agent-runs/{run_id}")) {
		t.Error("an appended-identifier tail must match a parameter segment")
	}
	if !clusterPathMatches("/api/v1/credentials/proxmox/{}*", route("/api/v1/credentials/proxmox/{credential_id}/tailscale")) {
		t.Error("an appended-identifier tail must match a parameter segment with more route after it")
	}
	if clusterPathMatches("/api/v1/credentials/proxmox/{}*", route("/api/v1/credentials/proxmox/ssh-keys")) {
		t.Error("an appended-identifier tail must not match a literal route segment")
	}
	if !clusterPathMatches("/api/v1/clusters/{}/nodes/{}/restart", route("/api/v1/clusters/{cluster_id}/nodes/{node_id}/restart")) {
		t.Error("a placeholder must match a parameter segment")
	}
	if !clusterPathMatches("/api/v1/clusters/{}/k8s/api/v1/pods", "/api/v1/clusters/{}/k8s/*") {
		t.Error("a trailing star must swallow the rest")
	}
	if clusterPathMatches("/api/v1/org/runs", "/api/v1/org/runs/{}") {
		t.Error("a shorter call path must not match a longer route")
	}
	if clusterPathMatches("/api/v1/org/clusters/{}/cost", "/api/v1/org/clusters/managed/cost") {
		t.Error("a dynamic call segment must not match a literal route segment: the real request would 404")
	}
}
