package client

// Every /api/v1 path the CLI builds must be a route the cluster binary
// registers.
//
// The client composes its requests from string literals
// (`c.BaseURL + "/api/v1/org/ai-agent-runs/" + runID`), so nothing types a
// path against anything and a renamed or removed route on the cluster side
// is a 404 for every user of that command. routes.json is the cluster repo's
// route census, generated by walking the real chi router (ankraio/cluster,
// docs/route-census.md), and it is the truth this test checks against. CI
// downloads it and points ANKRA_CLUSTER_ROUTES_JSON at it; locally:
//
//	ANKRA_CLUSTER_ROUTES_JSON=../cluster/routes.json go test ./internal/client/ -run ClusterRoutes
//
// Matching is path-only and shape-aware: a `{…}` segment on either side
// matches any single segment and a trailing `*` on a route matches the rest.
// A literal that ends in "/" is a prefix the code appends an identifier to,
// so it is checked as `prefix/{}`; a `%s` or `%d` placeholder is one dynamic
// segment. testdata/cluster_routes_allowlist.json is a ratchet: the paths
// that did not resolve when the check was introduced. A new one fails, a
// listed one that resolves fails too, so the list only shrinks. Regenerate
// it deliberately with ANKRA_CLUSTER_ROUTES_UPDATE=1.

import (
	"encoding/json"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"
)

type clusterRouteCensus struct {
	Routes []struct {
		Method  string `json:"method"`
		Path    string `json:"path"`
		Package string `json:"package"`
	} `json:"routes"`
}

var clusterRouteParameter = regexp.MustCompile(`\{[^}]*\}|%[sdv]`)

// normalizeClusterPath collapses every parameter to `{}`, treats a trailing
// slash as a dynamic tail, and ignores a query string.
func normalizeClusterPath(path string) string {
	withoutQuery := strings.SplitN(path, "?", 2)[0]
	if strings.HasSuffix(withoutQuery, "/") && len(withoutQuery) > 1 {
		withoutQuery += "{}"
	}
	collapsed := clusterRouteParameter.ReplaceAllString(withoutQuery, "{}")
	segments := strings.Split(collapsed, "/")
	for index, segment := range segments {
		if strings.Contains(segment, "{}") {
			segments[index] = "{}"
		}
	}
	return strings.Join(segments, "/")
}

// clusterPathMatches reports whether a normalized call path has the shape of a
// normalized route pattern.
func clusterPathMatches(callPath string, routePath string) bool {
	call := strings.Split(callPath, "/")
	route := strings.Split(routePath, "/")
	for index, routeSegment := range route {
		if routeSegment == "*" {
			return true
		}
		if index >= len(call) {
			return false
		}
		callSegment := call[index]
		if routeSegment == "{}" || callSegment == "{}" || routeSegment == callSegment {
			continue
		}
		return false
	}
	return len(call) == len(route)
}

// clusterPathLiterals returns every string literal in the module's non-test
// Go files that starts with /api/v1, with the file and line it was found in.
func clusterPathLiterals(t *testing.T, moduleRoot string) map[string][]string {
	t.Helper()
	found := map[string][]string{}
	fileSet := token.NewFileSet()
	walkError := filepath.WalkDir(moduleRoot, func(path string, entry os.DirEntry, walkError error) error {
		if walkError != nil {
			return walkError
		}
		if entry.IsDir() {
			if entry.Name() == ".git" || entry.Name() == "node_modules" || strings.HasPrefix(entry.Name(), ".") && path != moduleRoot {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			return nil
		}
		file, parseError := parser.ParseFile(fileSet, path, nil, 0)
		if parseError != nil {
			return parseError
		}
		relative, _ := filepath.Rel(moduleRoot, path)
		ast.Inspect(file, func(node ast.Node) bool {
			literal, isLiteral := node.(*ast.BasicLit)
			if !isLiteral || literal.Kind != token.STRING {
				return true
			}
			value, unquoteError := strconv.Unquote(literal.Value)
			if unquoteError != nil || !strings.HasPrefix(value, "/api/v1/") {
				return true
			}
			where := relative + ":" + strconv.Itoa(fileSet.Position(literal.Pos()).Line)
			found[value] = append(found[value], where)
			return true
		})
		return nil
	})
	if walkError != nil {
		t.Fatalf("scanning %s: %v", moduleRoot, walkError)
	}
	return found
}

// TestClusterRoutesAreRegistered checks every /api/v1 literal in the module
// against the cluster route census.
func TestClusterRoutesAreRegistered(t *testing.T) {
	censusPath := os.Getenv("ANKRA_CLUSTER_ROUTES_JSON")
	if censusPath == "" {
		t.Skip("ANKRA_CLUSTER_ROUTES_JSON is unset: point it at the cluster repo's routes.json to check the CLI's paths against the route census (CI does)")
	}
	raw, readError := os.ReadFile(censusPath)
	if readError != nil {
		t.Fatalf("reading the route census at %s: %v", censusPath, readError)
	}
	var census clusterRouteCensus
	if unmarshalError := json.Unmarshal(raw, &census); unmarshalError != nil {
		t.Fatalf("%s is not a route census: %v", censusPath, unmarshalError)
	}
	if len(census.Routes) == 0 {
		t.Fatalf("%s lists no routes", censusPath)
	}
	registered := map[string]bool{}
	for _, route := range census.Routes {
		registered[normalizeClusterPath(route.Path)] = true
	}
	var routeIndex []string
	for path := range registered {
		routeIndex = append(routeIndex, path)
	}

	literals := clusterPathLiterals(t, filepath.Join("..", ".."))
	var resolved, unresolved []string
	for value, locations := range literals {
		callPath := normalizeClusterPath(value)
		isRegistered := false
		for _, routePath := range routeIndex {
			if clusterPathMatches(callPath, routePath) {
				isRegistered = true
				break
			}
		}
		sort.Strings(locations)
		entry := value + "  (" + locations[0] + ")"
		if isRegistered {
			resolved = append(resolved, entry)
		} else {
			unresolved = append(unresolved, entry)
		}
	}
	sort.Strings(resolved)
	sort.Strings(unresolved)
	t.Logf("cluster routes: %d distinct /api/v1 literals checked against %d registered routes; %d resolved, %d unresolved",
		len(literals), len(census.Routes), len(resolved), len(unresolved))

	allowlistPath := filepath.Join("testdata", "cluster_routes_allowlist.json")
	if os.Getenv("ANKRA_CLUSTER_ROUTES_UPDATE") == "1" {
		encoded, marshalError := json.MarshalIndent(unresolved, "", "  ")
		if marshalError != nil {
			t.Fatalf("encoding the allowlist: %v", marshalError)
		}
		if mkdirError := os.MkdirAll(filepath.Dir(allowlistPath), 0o755); mkdirError != nil {
			t.Fatalf("creating testdata: %v", mkdirError)
		}
		if writeError := os.WriteFile(allowlistPath, append(encoded, '\n'), 0o644); writeError != nil {
			t.Fatalf("writing %s: %v", allowlistPath, writeError)
		}
		return
	}
	var allowlist []string
	allowRaw, allowReadError := os.ReadFile(allowlistPath)
	if allowReadError != nil {
		t.Fatalf("reading %s: %v (run once with ANKRA_CLUSTER_ROUTES_UPDATE=1 to create it)", allowlistPath, allowReadError)
	}
	if unmarshalError := json.Unmarshal(allowRaw, &allowlist); unmarshalError != nil {
		t.Fatalf("%s is not a JSON list of strings: %v", allowlistPath, unmarshalError)
	}
	allowed := map[string]bool{}
	for _, entry := range allowlist {
		allowed[entry] = true
	}
	current := map[string]bool{}
	for _, entry := range unresolved {
		current[entry] = true
	}
	var appeared, gone []string
	for _, entry := range unresolved {
		if !allowed[entry] {
			appeared = append(appeared, entry)
		}
	}
	for _, entry := range allowlist {
		if !current[entry] {
			gone = append(gone, entry)
		}
	}
	if len(appeared) > 0 {
		t.Errorf("%d /api/v1 path(s) the cluster router does not register (fix the path, add the route on the cluster side, or record it deliberately with ANKRA_CLUSTER_ROUTES_UPDATE=1):\n  %s",
			len(appeared), strings.Join(appeared, "\n  "))
	}
	if len(gone) > 0 {
		t.Errorf("%d allowlisted path(s) now resolve or moved; drop them so the list keeps shrinking (ANKRA_CLUSTER_ROUTES_UPDATE=1 rewrites it):\n  %s",
			len(gone), strings.Join(gone, "\n  "))
	}
}

// TestNormalizeClusterPath pins the shapes the matcher relies on.
func TestNormalizeClusterPath(t *testing.T) {
	cases := map[string]string{
		"/api/v1/org/ai-agent-runs/":                 "/api/v1/org/ai-agent-runs/{}",
		"/api/v1/clusters/%s/nodes/%s/restart":       "/api/v1/clusters/{}/nodes/{}/restart",
		"/api/v1/org/runs/{run_id}/stream?follow=1":  "/api/v1/org/runs/{}/stream",
		"/api/v1/clusters/{cluster_id}/k8s/*":        "/api/v1/clusters/{}/k8s/*",
		"/api/v1/org/stack-profiles/import-draft":    "/api/v1/org/stack-profiles/import-draft",
		"/api/v1/org/credentials/morpheus/ssh-key%s": "/api/v1/org/credentials/morpheus/{}",
	}
	for input, want := range cases {
		if got := normalizeClusterPath(input); got != want {
			t.Errorf("normalizeClusterPath(%q) = %q, want %q", input, got, want)
		}
	}
	if !clusterPathMatches("/api/v1/org/ai-agent-runs/{}", "/api/v1/org/ai-agent-runs/{run_id}") {
		t.Error("a dynamic tail must match a parameter segment")
	}
	if !clusterPathMatches("/api/v1/clusters/{}/k8s/api/v1/pods", "/api/v1/clusters/{}/k8s/*") {
		t.Error("a trailing star must swallow the rest")
	}
	if clusterPathMatches("/api/v1/org/runs", "/api/v1/org/runs/{}") {
		t.Error("a shorter call path must not match a longer route")
	}
}
