// Command gendocs renders the ankra CLI command tree as Mintlify MDX pages,
// one page per top-level command family, plus an index page.
//
// Usage:
//
//	go run ./tools/gendocs --out ../ankra-docs/reference/cli
//
// The output directory is wiped of *.mdx files before writing so removed
// commands disappear from the docs. Pages are deterministic (sorted) so the
// diff is reviewable.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"ankra/cmd"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func main() {
	out := flag.String("out", "", "directory to write MDX files into (required)")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "gendocs: --out is required")
		os.Exit(2)
	}

	root := cmd.Root()
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()

	if err := run(root, *out); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run(root *cobra.Command, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	stale, err := filepath.Glob(filepath.Join(outDir, "*.mdx"))
	if err != nil {
		return err
	}
	for _, f := range stale {
		if err := os.Remove(f); err != nil {
			return err
		}
	}

	families := visibleSubcommands(root)
	for _, family := range families {
		page := renderFamilyPage(family)
		name := family.Name() + ".mdx"
		if err := os.WriteFile(filepath.Join(outDir, name), []byte(page), 0o644); err != nil {
			return err
		}
	}

	index := renderIndexPage(root, families)
	if err := os.WriteFile(filepath.Join(outDir, "index.mdx"), []byte(index), 0o644); err != nil {
		return err
	}

	fmt.Printf("gendocs: wrote %d command pages + index to %s\n", len(families), outDir)
	return nil
}

func visibleSubcommands(c *cobra.Command) []*cobra.Command {
	var cmds []*cobra.Command
	for _, sub := range c.Commands() {
		if sub.Hidden || sub.Name() == "help" {
			continue
		}
		cmds = append(cmds, sub)
	}
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].Name() < cmds[j].Name() })
	return cmds
}

// escapeMDX makes arbitrary help text safe inside MDX prose: angle brackets
// and curly braces are JSX syntax to Mintlify.
func escapeMDX(s string) string {
	replacer := strings.NewReplacer(
		"<", "&lt;",
		">", "&gt;",
		"{", "&#123;",
		"}", "&#125;",
	)
	return replacer.Replace(s)
}

// escapeTableCell additionally escapes pipes so flag usage strings cannot
// break the markdown table layout.
func escapeTableCell(s string) string {
	return strings.ReplaceAll(escapeMDX(s), "|", "\\|")
}

func renderFamilyPage(family *cobra.Command) string {
	var b strings.Builder

	title := family.CommandPath()
	desc := strings.TrimSpace(family.Short)
	if desc == "" {
		desc = "Reference for the " + title + " command."
	}
	fmt.Fprintf(&b, "---\ntitle: \"%s\"\ndescription: \"%s\"\n---\n\n", title, strings.ReplaceAll(desc, `"`, `'`))
	b.WriteString("{/* Generated by ankra-cli tools/gendocs — do not edit by hand. */}\n\n")

	renderCommand(&b, family, 2)

	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		for _, sub := range visibleSubcommands(c) {
			renderCommand(&b, sub, 2)
			walk(sub)
		}
	}
	walk(family)

	return b.String()
}

func renderCommand(b *strings.Builder, c *cobra.Command, level int) {
	heading := strings.Repeat("#", level)
	fmt.Fprintf(b, "%s %s\n\n", heading, c.CommandPath())

	long := strings.TrimSpace(c.Long)
	short := strings.TrimSpace(c.Short)
	switch {
	case long != "":
		fmt.Fprintf(b, "%s\n\n", escapeMDX(long))
	case short != "":
		fmt.Fprintf(b, "%s\n\n", escapeMDX(short))
	}

	if c.Runnable() || len(c.Commands()) == 0 {
		fmt.Fprintf(b, "```bash\n%s\n```\n\n", c.UseLine())
	}

	if example := strings.TrimSpace(c.Example); example != "" {
		b.WriteString("**Examples**\n\n")
		fmt.Fprintf(b, "```bash\n%s\n```\n\n", example)
	}

	if flags := collectFlags(c.NonInheritedFlags()); len(flags) > 0 {
		b.WriteString("**Flags**\n\n")
		b.WriteString("| Flag | Default | Description |\n|------|---------|-------------|\n")
		for _, f := range flags {
			b.WriteString(f)
		}
		b.WriteString("\n")
	}
}

func collectFlags(fs *pflag.FlagSet) []string {
	var rows []string
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Name == "help" {
			return
		}
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name = "`-" + f.Shorthand + "`, " + name
		}
		def := f.DefValue
		if def == "" {
			def = " "
		} else {
			def = "`" + escapeTableCell(def) + "`"
		}
		rows = append(rows, fmt.Sprintf("| %s | %s | %s |\n", name, def, escapeTableCell(f.Usage)))
	})
	return rows
}

func renderIndexPage(root *cobra.Command, families []*cobra.Command) string {
	var b strings.Builder
	b.WriteString(`---
title: "CLI Command Reference"
description: "Every ankra CLI command, flag, and default — generated from the CLI source."
---

`)
	b.WriteString("{/* Generated by ankra-cli tools/gendocs — do not edit by hand. */}\n\n")
	fmt.Fprintf(&b, "This reference is generated from ankra CLI **v%s**. For installation and authentication, see the [CLI overview](/integrations/ankra-cli).\n\n", root.Version)

	b.WriteString("## Commands\n\n| Command | Description |\n|---------|-------------|\n")
	for _, f := range families {
		fmt.Fprintf(&b, "| [%s](/reference/cli/%s) | %s |\n", f.CommandPath(), f.Name(), escapeTableCell(strings.TrimSpace(f.Short)))
	}
	b.WriteString("\n## Global Flags\n\nThese flags are accepted by every command:\n\n")
	b.WriteString("| Flag | Default | Description |\n|------|---------|-------------|\n")
	for _, row := range collectFlags(root.PersistentFlags()) {
		b.WriteString(row)
	}
	b.WriteString("\n")
	return b.String()
}
