package cmd

import (
	"context"
	"io"

	"ankra/internal/client"
)

type APIClient interface {
	SetOrganisationOverride(orgID string)
	OrganisationOverride() string

	ListClusters(page int, pageSize int) (*client.ClusterListResponse, error)
	GetCluster(name string) (client.ClusterListItem, error)
	GetClusterByID(clusterID string) (client.ClusterListItem, error)
	DeleteCluster(ctx context.Context, name string) error
	TriggerReconcile(ctx context.Context, clusterID string) (*client.TriggerReconcileResult, error)
	ProvisionCluster(ctx context.Context, clusterID string) (*client.ProvisionClusterResult, error)
	DeprovisionCluster(ctx context.Context, clusterID string, autoDelete, force bool) (*client.DeprovisionClusterResult, error)
	RollToClusterResourceVersion(ctx context.Context, clusterID, versionID string) (*client.RollToClusterResourceVersionResult, error)
	ApplyCluster(ctx context.Context, clusterReq client.CreateImportClusterRequest, wait bool) (*client.ImportResponse, bool, error)
	ValidateCluster(ctx context.Context, spec client.CreateResourceSpec, strictSecrets bool, clusterID string) (*client.ValidateClusterResponse, error)
	CreateStackDraft(ctx context.Context, clusterID string, stack client.Stack) (*client.StackDraftResult, error)
	GetClusterKubeToken(ctx context.Context, clusterID string) (*client.KubeToken, error)
	ListClusterAccessGrants(ctx context.Context, clusterID string) (*client.ListClusterAccessGrantsResponse, error)
	CreateClusterAccessGrant(ctx context.Context, clusterID string, request client.CreateClusterAccessGrantRequest) (*client.CreateClusterAccessGrantResponse, error)
	DeleteClusterAccessGrant(ctx context.Context, clusterID string, grantID string) (*client.DeleteClusterAccessGrantResponse, error)

	ListClusterAddons(clusterID string) ([]client.ClusterAddonListItem, error)
	ListAvailableAddons(clusterID string) ([]client.AvailableAddon, error)
	GetAddonSettings(clusterID, addonName string) (*client.GetAddonSettingsResponse, error)
	UpdateAddonSettings(ctx context.Context, clusterID, addonName string, settings client.AddonSettings) error
	GetAddonByName(clusterID, addonName string) (*client.ClusterAddonListItem, error)
	GetClusterAddonValues(ctx context.Context, clusterID, addonName string) (string, error)
	UninstallAddon(ctx context.Context, clusterID, addonResourceID string, deletePermanently bool) (*client.UninstallAddonResult, error)

	ListExecutions(opts client.ListExecutionsOptions) (client.ExecutionListResponse, error)
	GetExecution(executionID string) (client.ExecutionDetail, error)
	ListExecutionSteps(executionID string) ([]client.ExecutionStep, error)
	CancelExecution(ctx context.Context, executionID string) (*client.CancelExecutionResponse, error)
	CancelExecutionStep(ctx context.Context, executionID, stepID string) (*client.CancelStepResponse, error)
	BatchCancelExecutions(ctx context.Context, executionIDs []string) (*client.BatchCancelExecutionsResponse, error)
	RetryExecution(ctx context.Context, executionID string) (*client.ExecutionSummary, error)

	GetClusterIaC(ctx context.Context, clusterID string) (string, error)
	PatchClusterStackPartial(ctx context.Context, clusterID, stackName string, body client.PatchStackRequest) (*client.PatchStackResult, error)

	GetSopsConfig() (*client.SopsConfigResult, error)
	EncryptYAML(yamlContent string, encryptedPaths []string) (string, error)
	DecryptYAML(encryptedYaml string) (string, error)

	ListClusterManifests(clusterID string) ([]client.ClusterManifestListItem, error)
	GetClusterManifestConfiguration(ctx context.Context, clusterID, manifestName string) (string, error)
	DisconnectManifest(ctx context.Context, clusterID, stackName, manifestName string) (*client.DisconnectManifestResult, error)

	ListOrganisationVariables(ctx context.Context) (*client.OrganisationVariablesListResult, error)
	CreateOrganisationVariable(ctx context.Context, name, value, description string) (*client.OrganisationVariableResult, error)
	UpdateOrganisationVariable(ctx context.Context, name, value, description string) (*client.OrganisationVariableResult, error)
	DeleteOrganisationVariable(ctx context.Context, name string) error

	ListClusterVariables(ctx context.Context, clusterID string) (*client.ClusterVariablesListResult, error)
	CreateClusterVariable(ctx context.Context, clusterID, name, value, description string) (*client.ClusterVariableResult, error)
	UpdateClusterVariable(ctx context.Context, clusterID, name, value, description string) (*client.ClusterVariableResult, error)
	DeleteClusterVariable(ctx context.Context, clusterID, name string) error

	CreateSupportTicket(ctx context.Context, req client.CreateSupportTicketRequest) (*client.SupportTicket, error)
	ReviewSupportTicket(ctx context.Context, req client.ReviewSupportTicketRequest) (*client.SupportTicketReview, error)
	ListSupportTickets(ctx context.Context, opts client.ListSupportTicketsOptions) (*client.SupportTicketListResponse, error)
	GetSupportTicket(ctx context.Context, ticketID string) (*client.SupportTicket, error)
	CommentSupportTicket(ctx context.Context, ticketID, comment string) (*client.SupportTicket, error)
	CloseSupportTicket(ctx context.Context, ticketID string) (*client.SupportTicket, error)
	UploadSupportAttachment(ctx context.Context, ticketID, filePath string) (*client.SupportTicket, error)

	ListClusterStacks(clusterID string) ([]client.ClusterStackListItem, error)
	CreateStack(ctx context.Context, clusterID, name, description string) (*client.CreateStackResult, error)
	DeleteStack(ctx context.Context, clusterID, stackName string) (*client.DeleteStackResult, error)
	RenameStack(ctx context.Context, clusterID, stackName, newName string) (*client.RenameStackResult, error)
	GetStackHistory(clusterID, stackName string) (*client.GetStackHistoryResponse, error)
	CloneStackToCluster(ctx context.Context, targetClusterID string, cloneReq client.CloneStackToClusterRequest) (*client.CloneStackToClusterResult, error)

	ListStackProfiles(page, pageSize int, search string) (*client.StackProfileListResponse, error)
	ExportStackProfileIac(profileID string, version int) (*client.StackProfileIacExport, error)
	ImportStackProfile(importRequest client.ImportStackProfileRequest) (*client.CreateStackProfileResult, error)
	GetStackProfile(profileID string) (*client.StackProfileDetail, error)
	InstantiateStackProfile(ctx context.Context, clusterID string, instantiateRequest client.InstantiateStackProfileRequest) (*client.InstantiateStackProfileResult, error)

	ListOrganisations() ([]client.OrganisationSummary, error)
	SwitchOrganisation(orgID string) (*client.SwitchOrganisationResponse, error)
	CreateOrganisation(name string, country *string) (*client.CreateOrganisationResponse, error)
	GetOrganisation(orgID string) (*client.OrganisationFull, error)
	InviteUserToOrganisation(inviteReq client.InviteUserRequest) (*client.InviteUserResponse, error)
	RemoveUserFromOrganisation(removeReq client.RemoveUserRequest) (*client.RemoveUserResponse, error)

	ListCredentials(provider *string) ([]client.Credential, error)
	ValidateCredentialName(name string) (*client.CredentialValidationResult, error)
	DeleteCredential(ctx context.Context, credentialID, organisationID string) (*client.DeleteCredentialResult, error)
	GetCredential(credentialID string) (*client.CredentialDetail, error)

	ListAPITokens() ([]client.APIToken, error)
	CreateAPIToken(name string, expiresAt *string) (*client.CreateAPITokenResponse, error)
	RevokeAPIToken(tokenID string) (*client.RevokeAPITokenResponse, error)
	DeleteAPIToken(tokenID string) (*client.DeleteAPITokenResponse, error)

	StreamChat(clusterID *string, chatReq client.ChatRequest) (<-chan client.ChatStreamEvent, error)
	ListChatHistory(clusterID *string, limit, offset int) (*client.ListConversationsResponse, error)
	GetChatConversation(conversationID string) (*client.ChatConversation, error)
	DeleteChatConversation(conversationID string) (*client.DeleteConversationResponse, error)
	GetClusterHealth(clusterID string, includeAI bool) (*client.ClusterHealth, error)

	ListCharts(page, pageSize int, onlySubscribed bool) (*client.ListChartsResponse, error)
	SearchCharts(query string) ([]client.ChartItem, error)
	GetChartDetails(chartName, repositoryURL string) (*client.ChartDetails, error)

	ListPods(clusterID string, opts *client.ListPodsOptions) (*client.ListPodsResponse, error)
	GetResources(clusterID string, req client.GetResourcesRequest) (*client.GetResourcesResponse, error)
	StreamPodLogs(ctx context.Context, clusterID string, opts client.PodLogOptions, writer io.Writer) error
	ListHelmReleases(clusterID string, opts *client.HelmReleasesOptions) (*client.HelmReleasesResponse, error)
	UninstallHelmRelease(clusterID, releaseName, namespace string) (*client.UninstallHelmReleaseResponse, error)
	QueryPrometheusInstant(clusterID, query string, timeoutSeconds int) (*client.PrometheusQueryResult, error)
	QueryPrometheusRange(clusterID string, opts client.PrometheusRangeOptions) (*client.PrometheusQueryResult, error)

	ListHelmRegistries() (*client.ListHelmRegistriesResponse, error)
	GetHelmRegistry(registryName string) (*client.GetHelmRegistryResponse, error)
	CreateHelmRegistry(req client.CreateHelmRegistryRequest) (*client.CreateHelmRegistryResponse, error)
	UpdateHelmRegistry(registryName string, readJobInterval *int) error
	DeleteHelmRegistry(registryName string) (*client.DeleteHelmRegistryResponse, error)
	SyncHelmRegistry(registryName string) (*client.SyncHelmRegistryResponse, error)
	ListHelmRegistrySyncJobs(registryName string, page, pageSize int) (*client.ListRegistrySyncJobsResponse, error)
	ListHelmRegistryCredentials() (*client.ListHelmCredentialsResponse, error)
	CreateHelmRegistryCredential(req client.CreateHelmCredentialRequest) (*client.CreateHelmCredentialResponse, error)
	GetHelmRegistryCredential(credentialName string) (*client.GetHelmCredentialResponse, error)
	UpdateHelmRegistryCredential(credentialName string, req client.UpdateHelmCredentialRequest) error
	DeleteHelmRegistryCredential(credentialName string) (*client.DeleteHelmCredentialResponse, error)

	GetClusterAgent(clusterID string) (*client.AgentInfo, error)
	GetAgentToken(clusterID string) (*client.AgentToken, error)
	GenerateAgentToken(ctx context.Context, clusterID string) (*client.AgentToken, error)
	UpgradeClusterAgent(ctx context.Context, clusterID string) (*client.UpgradeAgentResult, error)

	CreateHetznerCluster(req client.CreateHetznerClusterRequest) (*client.CreateHetznerClusterResponse, error)
	DeprovisionHetznerCluster(clusterID string, force bool) (*client.DeprovisionHetznerClusterResponse, error)
	GetHetznerWorkerCount(clusterID string) (*client.WorkerCountResult, error)
	ScaleHetznerWorkers(clusterID string, workerCount int) (*client.ScaleWorkersResult, error)
	GetHetznerK8sVersion(clusterID string) (*client.K8sVersionInfo, error)
	UpgradeHetznerK8sVersion(clusterID, targetVersion string) (*client.UpgradeK8sVersionResult, error)
	ListHetznerNodeGroups(clusterID string) (*client.NodeGroupListResult, error)
	AddHetznerNodeGroup(ctx context.Context, clusterID string, req client.AddNodeGroupRequest, wait bool) (*client.AddNodeGroupResult, bool, error)
	ScaleHetznerNodeGroup(ctx context.Context, clusterID, groupName string, count int, wait bool) (*client.ScaleNodeGroupResult, bool, error)
	UpdateHetznerNodeGroupInstanceType(ctx context.Context, clusterID, groupName, instanceType string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	DeleteHetznerNodeGroup(ctx context.Context, clusterID, groupName string, wait bool) (*client.DeleteNodeGroupResult, bool, error)
	GetHetznerControlPlane(clusterID string) (*client.ControlPlaneInfo, error)
	ChangeHetznerControlPlaneCount(clusterID string, count int) (*client.ChangeControlPlaneCountResult, error)
	ChangeHetznerControlPlaneInstanceType(clusterID, instanceType string) (*client.ChangeControlPlaneInstanceTypeResult, error)
	ListHetznerClusterNodes(clusterID string) (*client.NodeListResult, error)
	GetHetznerClusterNode(clusterID, nodeID string) (*client.NodeDetail, error)
	GetHetznerClusterSSHKeys(clusterID string) (*client.ClusterSSHKeysResult, error)
	UpdateHetznerClusterSSHKeys(clusterID string, sshKeyCredentialIDs []string) (*client.UpdateClusterSSHKeysResult, error)
	ResyncHetznerClusterSSHKeys(clusterID string) (*client.ResyncSSHKeysResult, error)

	ListHetznerCredentials() ([]client.HetznerCredentialListItem, error)
	CreateHetznerCredential(req client.CreateHetznerCredentialRequest) (*client.CreateHetznerCredentialResponse, error)
	ListSSHKeyCredentials() ([]client.HetznerCredentialListItem, error)
	CreateSSHKeyCredential(req client.CreateSSHKeyCredentialRequest) (*client.CreateSSHKeyCredentialResponse, error)

	CreateOvhCluster(req client.CreateOvhClusterRequest) (*client.CreateOvhClusterResponse, error)
	DeprovisionOvhCluster(clusterID string) (*client.DeprovisionOvhClusterResponse, error)
	StopOvhCluster(clusterID string) (*client.StopOvhClusterResponse, error)
	StartOvhCluster(clusterID, scope string) (*client.StartOvhClusterResult, error)
	GetOvhClusterSSHKeys(clusterID string) (*client.ClusterSSHKeysResult, error)
	UpdateOvhClusterSSHKeys(clusterID string, sshKeyCredentialIDs []string) (*client.UpdateClusterSSHKeysResult, error)
	ResyncOvhClusterSSHKeys(clusterID string) (*client.ResyncSSHKeysResult, error)
	GetOvhAccessInfo(clusterID string) (*client.ClusterAccessInfo, error)
	GetOvhWorkerCount(clusterID string) (*client.WorkerCountResult, error)
	ScaleOvhWorkers(clusterID string, workerCount int) (*client.ScaleWorkersResult, error)
	GetOvhK8sVersion(clusterID string) (*client.K8sVersionInfo, error)
	UpgradeOvhK8sVersion(clusterID, targetVersion string) (*client.UpgradeK8sVersionResult, error)
	ListOvhRegions(credentialID string) (*client.OvhRegionListResult, error)
	ListHetznerLocations(credentialID string) ([]client.HetznerLocation, error)
	ListHetznerServerTypes(credentialID, location string) ([]client.HetznerServerType, error)
	ListK3sVersions() (*client.ListK3sVersionsResult, error)
	ListOvhNodeGroups(clusterID string) (*client.NodeGroupListResult, error)
	AddOvhNodeGroup(ctx context.Context, clusterID string, req client.AddNodeGroupRequest, wait bool) (*client.AddNodeGroupResult, bool, error)
	ScaleOvhNodeGroup(ctx context.Context, clusterID, groupName string, count int, wait bool) (*client.ScaleNodeGroupResult, bool, error)
	UpdateOvhNodeGroupInstanceType(ctx context.Context, clusterID, groupName, instanceType string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	UpdateOvhNodeGroupLabels(ctx context.Context, clusterID, groupName string, labels map[string]string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	UpdateOvhNodeGroupTaints(ctx context.Context, clusterID, groupName string, taints []client.NodeTaint, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	DeleteOvhNodeGroup(ctx context.Context, clusterID, groupName string, wait bool) (*client.DeleteNodeGroupResult, bool, error)
	GetOvhControlPlane(clusterID string) (*client.ControlPlaneInfo, error)
	ChangeOvhControlPlaneCount(clusterID string, count int) (*client.ChangeControlPlaneCountResult, error)
	ChangeOvhControlPlaneInstanceType(clusterID, instanceType string) (*client.ChangeControlPlaneInstanceTypeResult, error)
	ListOvhClusterNodes(clusterID string) (*client.NodeListResult, error)
	GetOvhClusterNode(clusterID, nodeID string) (*client.NodeDetail, error)

	ListOvhCredentials() ([]client.OvhCredentialListItem, error)
	CreateOvhCredential(req client.CreateOvhCredentialRequest) (*client.CreateOvhCredentialResponse, error)
	ListOvhSSHKeyCredentials() ([]client.OvhCredentialListItem, error)
	CreateOvhSSHKeyCredential(req client.CreateSSHKeyCredentialRequest) (*client.CreateSSHKeyCredentialResponse, error)

	CreateUpcloudCluster(req client.CreateUpcloudClusterRequest) (*client.CreateUpcloudClusterResponse, error)
	DeprovisionUpcloudCluster(clusterID string) (*client.DeprovisionUpcloudClusterResponse, error)
	StopUpcloudCluster(clusterID string) (*client.StopUpcloudClusterResponse, error)
	StartUpcloudCluster(clusterID, scope string) (*client.StartUpcloudClusterResult, error)
	GetUpcloudWorkerCount(clusterID string) (*client.WorkerCountResult, error)
	ScaleUpcloudWorkers(clusterID string, workerCount int) (*client.ScaleWorkersResult, error)
	GetUpcloudK8sVersion(clusterID string) (*client.K8sVersionInfo, error)
	UpgradeUpcloudK8sVersion(clusterID, targetVersion string) (*client.UpgradeK8sVersionResult, error)
	ListUpcloudNodeGroups(clusterID string) (*client.NodeGroupListResult, error)
	AddUpcloudNodeGroup(ctx context.Context, clusterID string, req client.AddNodeGroupRequest, wait bool) (*client.AddNodeGroupResult, bool, error)
	ScaleUpcloudNodeGroup(ctx context.Context, clusterID, groupName string, count int, wait bool) (*client.ScaleNodeGroupResult, bool, error)
	UpdateUpcloudNodeGroupInstanceType(ctx context.Context, clusterID, groupName, instanceType string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	DeleteUpcloudNodeGroup(ctx context.Context, clusterID, groupName string, wait bool) (*client.DeleteNodeGroupResult, bool, error)
	GetUpcloudControlPlane(clusterID string) (*client.ControlPlaneInfo, error)
	ChangeUpcloudControlPlaneCount(clusterID string, count int) (*client.ChangeControlPlaneCountResult, error)
	ChangeUpcloudControlPlaneInstanceType(clusterID, instanceType string) (*client.ChangeControlPlaneInstanceTypeResult, error)
	ListUpcloudClusterNodes(clusterID string) (*client.NodeListResult, error)
	GetUpcloudClusterNode(clusterID, nodeID string) (*client.NodeDetail, error)
	GetUpcloudClusterSSHKeys(clusterID string) (*client.ClusterSSHKeysResult, error)
	UpdateUpcloudClusterSSHKeys(clusterID string, sshKeyCredentialIDs []string) (*client.UpdateClusterSSHKeysResult, error)
	ResyncUpcloudClusterSSHKeys(clusterID string) (*client.ResyncSSHKeysResult, error)

	ListUpcloudCredentials() ([]client.UpcloudCredentialListItem, error)
	CreateUpcloudCredential(req client.CreateUpcloudCredentialRequest) (*client.CreateUpcloudCredentialResponse, error)
	ListUpcloudSSHKeyCredentials() ([]client.UpcloudCredentialListItem, error)
	CreateUpcloudSSHKeyCredential(req client.CreateSSHKeyCredentialRequest) (*client.CreateSSHKeyCredentialResponse, error)
}
