package cmd

import (
	"context"
	"encoding/json"
	"io"

	"ankra/internal/client"
)

type APIClient interface {
	SetOrganisationOverride(orgID string)
	OrganisationOverride() string

	ListClusters(page int, pageSize int) (*client.ClusterListResponse, error)
	GetCluster(name string) (client.ClusterListItem, error)
	GetClusterByID(clusterID string) (client.ClusterListItem, error)
	DeleteCluster(ctx context.Context, name string) error
	TriggerReconcile(ctx context.Context, clusterID string) (*client.TriggerReconcileResult, error)
	ProvisionCluster(ctx context.Context, clusterID string) (*client.ProvisionClusterResult, error)
	DeprovisionCluster(ctx context.Context, clusterID string, autoDelete, force bool) (*client.DeprovisionClusterResult, error)
	RollToClusterResourceVersion(ctx context.Context, clusterID, versionID string) (*client.RollToClusterResourceVersionResult, error)
	ApplyCluster(ctx context.Context, clusterReq client.CreateImportClusterRequest, wait bool) (*client.ImportResponse, bool, error)
	ValidateCluster(ctx context.Context, spec client.CreateResourceSpec, strictSecrets bool, clusterID string) (*client.ValidateClusterResponse, error)
	CreateStackDraft(ctx context.Context, clusterID string, stack client.Stack) (*client.StackDraftResult, error)
	GetClusterKubeToken(ctx context.Context, clusterID string) (*client.KubeToken, error)
	ListClusterAccessGrants(ctx context.Context, clusterID string) (*client.ListClusterAccessGrantsResponse, error)
	CreateClusterAccessGrant(ctx context.Context, clusterID string, request client.CreateClusterAccessGrantRequest) (*client.CreateClusterAccessGrantResponse, error)
	DeleteClusterAccessGrant(ctx context.Context, clusterID string, grantID string) (*client.DeleteClusterAccessGrantResponse, error)

	ListClusterAddons(clusterID string) ([]client.ClusterAddonListItem, error)
	ListAvailableAddons(clusterID string) ([]client.AvailableAddon, error)
	GetAddonSettings(clusterID, addonName string) (*client.GetAddonSettingsResponse, error)
	UpdateAddonSettings(ctx context.Context, clusterID, addonName string, settings client.AddonSettings) error
	GetAddonByName(clusterID, addonName string) (*client.ClusterAddonListItem, error)
	GetClusterAddonValues(ctx context.Context, clusterID, addonName string) (string, error)
	UninstallAddon(ctx context.Context, clusterID, addonResourceID string, deletePermanently bool) (*client.UninstallAddonResult, error)

	ListExecutions(opts client.ListExecutionsOptions) (client.ExecutionListResponse, error)
	GetExecution(executionID string) (client.ExecutionDetail, error)
	EnrichExecutionDetailWithDrift(detail *client.ExecutionDetail) error
	ListExecutionSteps(executionID string) ([]client.ExecutionStep, error)
	CancelExecution(ctx context.Context, executionID string) (*client.CancelExecutionResponse, error)
	CancelExecutionStep(ctx context.Context, executionID, stepID string) (*client.CancelStepResponse, error)
	BatchCancelExecutions(ctx context.Context, executionIDs []string) (*client.BatchCancelExecutionsResponse, error)
	RetryExecution(ctx context.Context, executionID string) (*client.ExecutionSummary, error)

	GetClusterIaC(ctx context.Context, clusterID string) (string, error)
	PatchClusterStackPartial(ctx context.Context, clusterID, stackName string, body client.PatchStackRequest) (*client.PatchStackResult, error)

	GetSopsConfig() (*client.SopsConfigResult, error)
	EncryptYAML(yamlContent string, encryptedPaths []string) (string, error)
	DecryptYAML(encryptedYaml string) (string, error)

	ListClusterManifests(clusterID string) ([]client.ClusterManifestListItem, error)
	GetClusterManifestConfiguration(ctx context.Context, clusterID, manifestName string) (string, error)
	DisconnectManifest(ctx context.Context, clusterID, stackName, manifestName string) (*client.DisconnectManifestResult, error)

	ListOrganisationVariables(ctx context.Context) (*client.OrganisationVariablesListResult, error)
	CreateOrganisationVariable(ctx context.Context, name, value, description string) (*client.OrganisationVariableResult, error)
	UpdateOrganisationVariable(ctx context.Context, name, value, description string) (*client.OrganisationVariableResult, error)
	DeleteOrganisationVariable(ctx context.Context, name string) error

	ListClusterVariables(ctx context.Context, clusterID string) (*client.ClusterVariablesListResult, error)
	CreateClusterVariable(ctx context.Context, clusterID, name, value, description string) (*client.ClusterVariableResult, error)
	UpdateClusterVariable(ctx context.Context, clusterID, name, value, description string) (*client.ClusterVariableResult, error)
	DeleteClusterVariable(ctx context.Context, clusterID, name string) error

	CreateSupportTicket(ctx context.Context, req client.CreateSupportTicketRequest) (*client.SupportTicket, error)
	ReviewSupportTicket(ctx context.Context, req client.ReviewSupportTicketRequest) (*client.SupportTicketReview, error)
	ListSupportTickets(ctx context.Context, opts client.ListSupportTicketsOptions) (*client.SupportTicketListResponse, error)
	GetSupportTicket(ctx context.Context, ticketID string) (*client.SupportTicket, error)
	CommentSupportTicket(ctx context.Context, ticketID, comment string) (*client.SupportTicket, error)
	CloseSupportTicket(ctx context.Context, ticketID string) (*client.SupportTicket, error)
	UploadSupportAttachment(ctx context.Context, ticketID, filePath string) (*client.SupportTicket, error)

	ListClusterStacks(clusterID string) ([]client.ClusterStackListItem, error)
	DeleteStack(ctx context.Context, clusterID, stackName string) (*client.DeleteStackResult, error)
	RenameStack(ctx context.Context, clusterID, stackName, newName string) (*client.RenameStackResult, error)
	GetStackHistory(clusterID, stackName string) (*client.GetStackHistoryResponse, error)
	CloneStackToCluster(ctx context.Context, targetClusterID string, cloneReq client.CloneStackToClusterRequest) (*client.CloneStackToClusterResult, error)

	ListStackProfiles(page, pageSize int, search string, category string) (*client.StackProfileListResponse, error)
	ExportStackProfileIac(profileID string, version int) (*client.StackProfileIacExport, error)
	ImportStackProfile(importRequest client.ImportStackProfileRequest) (*client.CreateStackProfileResult, error)
	GetStackProfile(profileID string) (*client.StackProfileDetail, error)
	InstantiateStackProfile(ctx context.Context, clusterID string, instantiateRequest client.InstantiateStackProfileRequest) (*client.InstantiateStackProfileResult, error)

	CreateApplication(requestContext context.Context, applicationRequest client.CreateApplicationRequest) (*client.CreateApplicationResponse, error)
	ListApplicationsRaw(requestContext context.Context, page int, pageSize int, search string) (json.RawMessage, error)
	GetApplicationRaw(requestContext context.Context, applicationID string) (json.RawMessage, error)
	GetApplicationJobs(requestContext context.Context, applicationID string, page int, pageSize int) (json.RawMessage, error)
	RetryApplication(requestContext context.Context, applicationID string) (json.RawMessage, error)
	ReconcileApplication(requestContext context.Context, applicationID string) (json.RawMessage, error)
	DeleteApplication(requestContext context.Context, applicationID string) (json.RawMessage, error)
	DeployApplication(requestContext context.Context, applicationID string, deployRequest client.DeployApplicationRequest) (json.RawMessage, error)
	GetApplicationDeployments(requestContext context.Context, applicationID string) (json.RawMessage, error)
	GetApplicationInstallations(requestContext context.Context, applicationID string) (json.RawMessage, error)
	GetApplicationChartVersions(requestContext context.Context, applicationID string) (json.RawMessage, error)
	GetApplicationExistingPlatform(requestContext context.Context, applicationID string, clusterID string) (json.RawMessage, error)
	GetApplicationWorkflowRuns(requestContext context.Context, applicationID string, status string, page int, pageSize int) (json.RawMessage, error)
	GetApplicationWorkflowRunJobs(requestContext context.Context, applicationID string, runID int64) (json.RawMessage, error)
	RerunApplicationWorkflowRun(requestContext context.Context, applicationID string, runID int64) (json.RawMessage, error)
	GetApplicationPullRequestReviews(requestContext context.Context, applicationID string, limit int) (json.RawMessage, error)
	UpgradeApplicationWorkflow(requestContext context.Context, applicationID string) (json.RawMessage, error)
	GetApplicationBranches(requestContext context.Context, applicationID string) (json.RawMessage, error)
	GetApplicationBranchFiles(requestContext context.Context, applicationID string) (json.RawMessage, error)
	UpdateApplicationFiles(requestContext context.Context, applicationID string, filesRequest client.UpdateApplicationFilesRequest) (json.RawMessage, error)
	GetApplicationPublishReadiness(requestContext context.Context, applicationID string) (json.RawMessage, error)
	GetApplicationContainerSecurity(requestContext context.Context, applicationID string) (json.RawMessage, error)
	GetApplicationCodeSecurity(requestContext context.Context, applicationID string) (json.RawMessage, error)
	GetApplicationPackageVisibility(requestContext context.Context, applicationID string) (json.RawMessage, error)
	SetApplicationPackageVisibility(requestContext context.Context, applicationID string, visibilityRequest client.SetApplicationPackageVisibilityRequest) (json.RawMessage, error)
	MakeApplicationPackagesPublic(requestContext context.Context, applicationID string) (json.RawMessage, error)
	GetApplicationDemos(requestContext context.Context, applicationID string) (json.RawMessage, error)
	CheckApplicationDemoBuild(requestContext context.Context, applicationID string, branch string) (json.RawMessage, error)
	DeployApplicationDemo(requestContext context.Context, applicationID string, demoRequest client.DeployApplicationDemoRequest) (json.RawMessage, error)
	StopApplicationDemo(requestContext context.Context, applicationID string, workspaceID string) (json.RawMessage, error)

	ListOrganisations() ([]client.OrganisationSummary, error)
	SwitchOrganisation(orgID string) (*client.SwitchOrganisationResponse, error)
	CreateOrganisation(name string, country *string) (*client.CreateOrganisationResponse, error)
	GetOrganisation(orgID string) (*client.OrganisationFull, error)
	InviteUserToOrganisation(inviteReq client.InviteUserRequest) (*client.InviteUserResponse, error)
	RemoveUserFromOrganisation(removeReq client.RemoveUserRequest) (*client.RemoveUserResponse, error)
	ListOrganisationUsers(orgID string) ([]client.OrganisationUser, error)

	ListRoles() ([]client.RoleDocument, error)
	CreateCustomRole(request client.CreateCustomRoleRequest) (*client.RoleDocument, error)
	ListMemberAssignments(ankraUserID string) ([]client.RoleAssignment, error)
	CreateRoleAssignment(request client.CreateRoleAssignmentRequest) (*client.RoleAssignment, error)
	DeleteRoleAssignment(assignmentID string) error
	ListClusterGroups() ([]client.ClusterGroup, error)
	CreateClusterGroup(request client.CreateClusterGroupRequest) (*client.ClusterGroup, error)
	SetClusterGroupMembers(groupID string, clusterIDs []string) error
	SetClusterGroupSelector(groupID string, selector map[string]string) error
	PreviewClusterGroup(groupID string) ([]string, error)

	ListCredentials(provider *string) ([]client.Credential, error)
	ValidateCredentialName(name string) (*client.CredentialValidationResult, error)
	DeleteCredential(ctx context.Context, credentialID, organisationID string) (*client.DeleteCredentialResult, error)
	GetCredential(credentialID string) (*client.CredentialDetail, error)

	ListAPITokens() ([]client.APIToken, error)
	CreateAPIToken(name string, expiresAt *string, scopes []string) (*client.CreateAPITokenResponse, error)
	RevokeAPIToken(tokenID string) (*client.RevokeAPITokenResponse, error)
	DeleteAPIToken(tokenID string) (*client.DeleteAPITokenResponse, error)
	GetMFAStatus() (*client.MFAStatus, error)
	StartTOTPEnrollment() (*client.StartTOTPEnrollmentResponse, error)
	ConfirmTOTPEnrollment(code string) (*client.RecoveryCodesResponse, error)
	RemoveMFAMethod(methodID string) (*client.RemoveMFAResponse, error)
	RegenerateRecoveryCodes() (*client.RecoveryCodesResponse, error)
	RemovePasskey(credentialID string) (*client.RemoveMFAResponse, error)

	StreamChat(clusterID *string, chatReq client.ChatRequest) (<-chan client.ChatStreamEvent, error)
	ListChatHistory(clusterID *string, limit, offset int) (*client.ListConversationsResponse, error)
	GetChatConversation(conversationID string) (*client.ChatConversation, error)
	DeleteChatConversation(conversationID string) (*client.DeleteConversationResponse, error)
	GetClusterHealth(clusterID string, includeAI bool) (*client.ClusterHealth, error)

	ListAgentRuns(taskID string, statuses []string, limit int) (*client.AgentRunListResponse, error)
	GetAgentRun(runID string) (*client.AgentRun, error)
	GetAgentRunTranscript(runID string, since int64, limit int) (*client.AgentRunTranscript, error)
	CancelAgentRun(runID string) (*client.CancelAgentRunResponse, error)

	GetAIProviderStatus() (*client.AIProviderStatus, error)
	SetAIProvider(provider string) (*client.AIProviderStatus, error)
	SaveAnthropicKey(apiKey string) (*client.AIAnthropicStatus, error)
	DeleteAnthropicKey() (*client.AIAnthropicStatus, error)
	SaveOpenAICompatible(baseURL, apiKey, model string) (*client.AIOpenAICompatibleStatus, error)
	DeleteOpenAICompatible() (*client.AIOpenAICompatibleStatus, error)
	ListAIModels() ([]client.AICatalogModel, error)
	CreateAIModel(request client.AIModelRequest) (*client.AICatalogModel, error)
	UpdateAIModel(reference string, request client.AIModelRequest) (*client.AICatalogModel, error)
	DeleteAIModel(reference string) error
	ResetAIModels() ([]client.AICatalogModel, error)
	ListAIEndpoints() ([]client.AIEndpoint, error)
	CreateAIEndpoint(name, baseURL, apiKey string) (*client.AIEndpoint, error)
	UpdateAIEndpoint(endpointID, name, baseURL, apiKey string) (*client.AIEndpoint, error)
	DeleteAIEndpoint(endpointID string) error
	DiscoverEndpointModels(endpointID string) ([]string, error)

	ListCharts(page, pageSize int, onlySubscribed bool) (*client.ListChartsResponse, error)
	SearchCharts(query string) ([]client.ChartItem, error)
	GetChartDetails(chartName, repositoryURL string) (*client.ChartDetails, error)

	ListPods(clusterID string, opts *client.ListPodsOptions) (*client.ListPodsResponse, error)
	GetResources(clusterID string, req client.GetResourcesRequest) (*client.GetResourcesResponse, error)
	StreamPodLogs(ctx context.Context, clusterID string, opts client.PodLogOptions, writer io.Writer) error
	ListHelmReleases(clusterID string, opts *client.HelmReleasesOptions) (*client.HelmReleasesResponse, error)
	UninstallHelmRelease(clusterID, releaseName, namespace string) (*client.UninstallHelmReleaseResponse, error)
	QueryPrometheusInstant(clusterID, query string, timeoutSeconds int) (*client.PrometheusQueryResult, error)
	QueryPrometheusRange(clusterID string, opts client.PrometheusRangeOptions) (*client.PrometheusQueryResult, error)

	ListHelmRegistries() (*client.ListHelmRegistriesResponse, error)
	GetHelmRegistry(registryName string) (*client.GetHelmRegistryResponse, error)
	CreateHelmRegistry(req client.CreateHelmRegistryRequest) (*client.CreateHelmRegistryResponse, error)
	UpdateHelmRegistry(registryName string, readJobInterval *int) error
	DeleteHelmRegistry(registryName string) (*client.DeleteHelmRegistryResponse, error)
	SyncHelmRegistry(registryName string) (*client.SyncHelmRegistryResponse, error)
	ListHelmRegistrySyncJobs(registryName string, page, pageSize int) (*client.ListRegistrySyncJobsResponse, error)
	ListHelmRegistryCredentials() (*client.ListHelmCredentialsResponse, error)
	CreateHelmRegistryCredential(req client.CreateHelmCredentialRequest) (*client.CreateHelmCredentialResponse, error)
	GetHelmRegistryCredential(credentialName string) (*client.GetHelmCredentialResponse, error)
	UpdateHelmRegistryCredential(credentialName string, req client.UpdateHelmCredentialRequest) error
	DeleteHelmRegistryCredential(credentialName string) (*client.DeleteHelmCredentialResponse, error)

	GetClusterAgent(clusterID string) (*client.AgentInfo, error)
	GetAgentToken(clusterID string) (*client.AgentToken, error)
	GenerateAgentToken(ctx context.Context, clusterID string) (*client.AgentToken, error)
	UpgradeClusterAgent(ctx context.Context, clusterID string) (*client.UpgradeAgentResult, error)

	CreateHetznerCluster(req client.CreateHetznerClusterRequest) (*client.CreateHetznerClusterResponse, error)
	DeprovisionHetznerCluster(clusterID string, force bool) (*client.DeprovisionHetznerClusterResponse, error)
	StopHetznerCluster(clusterID string) (*client.ProviderStopClusterResponse, error)
	StartHetznerCluster(clusterID, scope string) (*client.ProviderStartClusterResult, error)
	GetHetznerWorkerCount(clusterID string) (*client.WorkerCountResult, error)
	ScaleHetznerWorkers(clusterID string, workerCount int) (*client.ScaleWorkersResult, error)
	GetHetznerK8sVersion(clusterID string) (*client.K8sVersionInfo, error)
	UpgradeHetznerK8sVersion(clusterID, targetVersion string, force bool) (*client.UpgradeK8sVersionResult, error)
	ListHetznerNodeGroups(clusterID string) (*client.NodeGroupListResult, error)
	AddHetznerNodeGroup(ctx context.Context, clusterID string, req client.AddNodeGroupRequest, wait bool) (*client.AddNodeGroupResult, bool, error)
	ScaleHetznerNodeGroup(ctx context.Context, clusterID, groupName string, count int, wait bool) (*client.ScaleNodeGroupResult, bool, error)
	UpdateHetznerNodeGroupInstanceType(ctx context.Context, clusterID, groupName, instanceType string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	DeleteHetznerNodeGroup(ctx context.Context, clusterID, groupName string, wait bool) (*client.DeleteNodeGroupResult, bool, error)
	GetHetznerNodeGroupAutoscaling(clusterID, groupName string) (*client.NodeGroupAutoscalingResult, error)
	UpdateHetznerNodeGroupAutoscaling(ctx context.Context, clusterID, groupName string, req client.NodeGroupAutoscalingRequest, wait bool) (*client.NodeGroupAutoscalingResult, bool, error)
	UpdateHetznerNodeGroupLabels(ctx context.Context, clusterID, groupName string, labels map[string]string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	UpdateHetznerNodeGroupTaints(ctx context.Context, clusterID, groupName string, taints []client.NodeTaint, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	GetHetznerControlPlane(clusterID string) (*client.ControlPlaneInfo, error)
	ChangeHetznerControlPlaneCount(clusterID string, count int) (*client.ChangeControlPlaneCountResult, error)
	ChangeHetznerControlPlaneInstanceType(clusterID, instanceType string) (*client.ChangeControlPlaneInstanceTypeResult, error)
	ListHetznerClusterNodes(clusterID string) (*client.NodeListResult, error)
	GetHetznerClusterNode(clusterID, nodeID string) (*client.NodeDetail, error)
	RestartHetznerClusterNode(clusterID, nodeID string) (*client.RestartNodeResult, error)
	UpdateHetznerBastionInstanceType(ctx context.Context, clusterID, instanceType string, wait bool) (*client.UpdateBastionInstanceTypeResult, bool, error)
	GetHetznerClusterSSHKeys(clusterID string) (*client.ClusterSSHKeysResult, error)
	UpdateHetznerClusterSSHKeys(clusterID string, sshKeyCredentialIDs []string) (*client.UpdateClusterSSHKeysResult, error)
	ResyncHetznerClusterSSHKeys(clusterID string) (*client.ResyncSSHKeysResult, error)

	ListHetznerCredentials() ([]client.HetznerCredentialListItem, error)
	CreateHetznerCredential(req client.CreateHetznerCredentialRequest) (*client.CreateHetznerCredentialResponse, error)
	ListSSHKeyCredentials() ([]client.HetznerCredentialListItem, error)
	CreateSSHKeyCredential(req client.CreateSSHKeyCredentialRequest) (*client.CreateSSHKeyCredentialResponse, error)

	CreateOvhCluster(req client.CreateOvhClusterRequest) (*client.CreateOvhClusterResponse, error)
	DeprovisionOvhCluster(clusterID string) (*client.DeprovisionOvhClusterResponse, error)
	StopOvhCluster(clusterID string) (*client.StopOvhClusterResponse, error)
	StartOvhCluster(clusterID, scope string) (*client.StartOvhClusterResult, error)
	GetOvhClusterSSHKeys(clusterID string) (*client.ClusterSSHKeysResult, error)
	UpdateOvhClusterSSHKeys(clusterID string, sshKeyCredentialIDs []string) (*client.UpdateClusterSSHKeysResult, error)
	ResyncOvhClusterSSHKeys(clusterID string) (*client.ResyncSSHKeysResult, error)
	GetOvhAccessInfo(clusterID string) (*client.ClusterAccessInfo, error)
	GetOvhWorkerCount(clusterID string) (*client.WorkerCountResult, error)
	ScaleOvhWorkers(clusterID string, workerCount int) (*client.ScaleWorkersResult, error)
	GetOvhK8sVersion(clusterID string) (*client.K8sVersionInfo, error)
	UpgradeOvhK8sVersion(clusterID, targetVersion string, force bool) (*client.UpgradeK8sVersionResult, error)
	ListOvhRegions(credentialID string) (*client.OvhRegionListResult, error)
	ListHetznerLocations(credentialID string) ([]client.HetznerLocation, error)
	ListHetznerServerTypes(credentialID, location string) ([]client.HetznerServerType, error)
	ListK3sVersions() (*client.ListVersionsResult, error)
	ListKubeadmVersions() (*client.ListVersionsResult, error)
	ListOvhNodeGroups(clusterID string) (*client.NodeGroupListResult, error)
	AddOvhNodeGroup(ctx context.Context, clusterID string, req client.AddNodeGroupRequest, wait bool) (*client.AddNodeGroupResult, bool, error)
	ScaleOvhNodeGroup(ctx context.Context, clusterID, groupName string, count int, wait bool) (*client.ScaleNodeGroupResult, bool, error)
	UpdateOvhNodeGroupInstanceType(ctx context.Context, clusterID, groupName, instanceType string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	UpdateOvhNodeGroupLabels(ctx context.Context, clusterID, groupName string, labels map[string]string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	UpdateOvhNodeGroupTaints(ctx context.Context, clusterID, groupName string, taints []client.NodeTaint, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	DeleteOvhNodeGroup(ctx context.Context, clusterID, groupName string, wait bool) (*client.DeleteNodeGroupResult, bool, error)
	GetOvhNodeGroupAutoscaling(clusterID, groupName string) (*client.NodeGroupAutoscalingResult, error)
	UpdateOvhNodeGroupAutoscaling(ctx context.Context, clusterID, groupName string, req client.NodeGroupAutoscalingRequest, wait bool) (*client.NodeGroupAutoscalingResult, bool, error)
	GetOvhControlPlane(clusterID string) (*client.ControlPlaneInfo, error)
	ChangeOvhControlPlaneCount(clusterID string, count int) (*client.ChangeControlPlaneCountResult, error)
	ChangeOvhControlPlaneInstanceType(clusterID, instanceType string) (*client.ChangeControlPlaneInstanceTypeResult, error)
	ListOvhClusterNodes(clusterID string) (*client.NodeListResult, error)
	GetOvhClusterNode(clusterID, nodeID string) (*client.NodeDetail, error)
	RestartOvhClusterNode(clusterID, nodeID string) (*client.RestartNodeResult, error)
	UpdateOvhBastionInstanceType(ctx context.Context, clusterID, instanceType string, wait bool) (*client.UpdateBastionInstanceTypeResult, bool, error)

	ListOvhCredentials() ([]client.OvhCredentialListItem, error)
	CreateOvhCredential(req client.CreateOvhCredentialRequest) (*client.CreateOvhCredentialResponse, error)
	ListOvhSSHKeyCredentials() ([]client.OvhCredentialListItem, error)
	CreateOvhSSHKeyCredential(req client.CreateSSHKeyCredentialRequest) (*client.CreateSSHKeyCredentialResponse, error)

	CreateUpcloudCluster(req client.CreateUpcloudClusterRequest) (*client.CreateUpcloudClusterResponse, error)
	DeprovisionUpcloudCluster(clusterID string) (*client.DeprovisionUpcloudClusterResponse, error)
	StopUpcloudCluster(clusterID string) (*client.StopUpcloudClusterResponse, error)
	StartUpcloudCluster(clusterID, scope string) (*client.StartUpcloudClusterResult, error)
	GetUpcloudWorkerCount(clusterID string) (*client.WorkerCountResult, error)
	ScaleUpcloudWorkers(clusterID string, workerCount int) (*client.ScaleWorkersResult, error)
	GetUpcloudK8sVersion(clusterID string) (*client.K8sVersionInfo, error)
	UpgradeUpcloudK8sVersion(clusterID, targetVersion string, force bool) (*client.UpgradeK8sVersionResult, error)
	ListUpcloudNodeGroups(clusterID string) (*client.NodeGroupListResult, error)
	AddUpcloudNodeGroup(ctx context.Context, clusterID string, req client.AddNodeGroupRequest, wait bool) (*client.AddNodeGroupResult, bool, error)
	ScaleUpcloudNodeGroup(ctx context.Context, clusterID, groupName string, count int, wait bool) (*client.ScaleNodeGroupResult, bool, error)
	UpdateUpcloudNodeGroupInstanceType(ctx context.Context, clusterID, groupName, instanceType string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	DeleteUpcloudNodeGroup(ctx context.Context, clusterID, groupName string, wait bool) (*client.DeleteNodeGroupResult, bool, error)
	GetUpcloudNodeGroupAutoscaling(clusterID, groupName string) (*client.NodeGroupAutoscalingResult, error)
	UpdateUpcloudNodeGroupAutoscaling(ctx context.Context, clusterID, groupName string, req client.NodeGroupAutoscalingRequest, wait bool) (*client.NodeGroupAutoscalingResult, bool, error)
	UpdateUpcloudNodeGroupLabels(ctx context.Context, clusterID, groupName string, labels map[string]string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	UpdateUpcloudNodeGroupTaints(ctx context.Context, clusterID, groupName string, taints []client.NodeTaint, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	GetUpcloudControlPlane(clusterID string) (*client.ControlPlaneInfo, error)
	ChangeUpcloudControlPlaneCount(clusterID string, count int) (*client.ChangeControlPlaneCountResult, error)
	ChangeUpcloudControlPlaneInstanceType(clusterID, instanceType string) (*client.ChangeControlPlaneInstanceTypeResult, error)
	ListUpcloudClusterNodes(clusterID string) (*client.NodeListResult, error)
	GetUpcloudClusterNode(clusterID, nodeID string) (*client.NodeDetail, error)
	RestartUpcloudClusterNode(clusterID, nodeID string) (*client.RestartNodeResult, error)
	UpdateUpcloudBastionInstanceType(ctx context.Context, clusterID, instanceType string, wait bool) (*client.UpdateBastionInstanceTypeResult, bool, error)
	GetUpcloudClusterSSHKeys(clusterID string) (*client.ClusterSSHKeysResult, error)
	UpdateUpcloudClusterSSHKeys(clusterID string, sshKeyCredentialIDs []string) (*client.UpdateClusterSSHKeysResult, error)
	ResyncUpcloudClusterSSHKeys(clusterID string) (*client.ResyncSSHKeysResult, error)

	ListUpcloudCredentials() ([]client.UpcloudCredentialListItem, error)
	CreateUpcloudCredential(req client.CreateUpcloudCredentialRequest) (*client.CreateUpcloudCredentialResponse, error)
	ListUpcloudSSHKeyCredentials() ([]client.UpcloudCredentialListItem, error)
	CreateUpcloudSSHKeyCredential(req client.CreateSSHKeyCredentialRequest) (*client.CreateSSHKeyCredentialResponse, error)

	CreateDigitaloceanCluster(req client.CreateDigitaloceanClusterRequest) (*client.CreateDigitaloceanClusterResponse, error)
	DeprovisionDigitaloceanCluster(clusterID string) (*client.DeprovisionDigitaloceanClusterResponse, error)
	StopDigitaloceanCluster(clusterID string) (*client.StopDigitaloceanClusterResponse, error)
	StartDigitaloceanCluster(clusterID, scope string) (*client.StartDigitaloceanClusterResult, error)
	GetDigitaloceanWorkerCount(clusterID string) (*client.WorkerCountResult, error)
	ScaleDigitaloceanWorkers(clusterID string, workerCount int) (*client.ScaleWorkersResult, error)
	GetDigitaloceanK8sVersion(clusterID string) (*client.K8sVersionInfo, error)
	UpgradeDigitaloceanK8sVersion(clusterID, targetVersion string, force bool) (*client.UpgradeK8sVersionResult, error)
	ListDigitaloceanNodeGroups(clusterID string) (*client.NodeGroupListResult, error)
	AddDigitaloceanNodeGroup(ctx context.Context, clusterID string, req client.AddNodeGroupRequest, wait bool) (*client.AddNodeGroupResult, bool, error)
	ScaleDigitaloceanNodeGroup(ctx context.Context, clusterID, groupName string, count int, wait bool) (*client.ScaleNodeGroupResult, bool, error)
	UpdateDigitaloceanNodeGroupInstanceType(ctx context.Context, clusterID, groupName, instanceType string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	GetDigitaloceanNodeGroupAutoscaling(clusterID, groupName string) (*client.NodeGroupAutoscalingResult, error)
	UpdateDigitaloceanNodeGroupAutoscaling(ctx context.Context, clusterID, groupName string, req client.NodeGroupAutoscalingRequest, wait bool) (*client.NodeGroupAutoscalingResult, bool, error)
	UpdateDigitaloceanNodeGroupLabels(ctx context.Context, clusterID, groupName string, labels map[string]string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	UpdateDigitaloceanNodeGroupTaints(ctx context.Context, clusterID, groupName string, taints []client.NodeTaint, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	DeleteDigitaloceanNodeGroup(ctx context.Context, clusterID, groupName string, wait bool) (*client.DeleteNodeGroupResult, bool, error)
	GetDigitaloceanControlPlane(clusterID string) (*client.ControlPlaneInfo, error)
	ChangeDigitaloceanControlPlaneCount(clusterID string, count int) (*client.ChangeControlPlaneCountResult, error)
	ChangeDigitaloceanControlPlaneInstanceType(clusterID, instanceType string) (*client.ChangeControlPlaneInstanceTypeResult, error)
	ListDigitaloceanClusterNodes(clusterID string) (*client.NodeListResult, error)
	GetDigitaloceanClusterNode(clusterID, nodeID string) (*client.NodeDetail, error)
	RestartDigitaloceanClusterNode(clusterID, nodeID string) (*client.RestartNodeResult, error)
	UpdateDigitaloceanBastionInstanceType(ctx context.Context, clusterID, instanceType string, wait bool) (*client.UpdateBastionInstanceTypeResult, bool, error)
	GetDigitaloceanClusterSSHKeys(clusterID string) (*client.ClusterSSHKeysResult, error)
	UpdateDigitaloceanClusterSSHKeys(clusterID string, sshKeyCredentialIDs []string) (*client.UpdateClusterSSHKeysResult, error)
	ResyncDigitaloceanClusterSSHKeys(clusterID string) (*client.ResyncSSHKeysResult, error)
	ListDigitaloceanRegions(credentialID string) ([]client.DigitaloceanRegion, error)
	ListDigitaloceanSizes(credentialID, region string) ([]client.DigitaloceanSize, error)

	ListDigitaloceanCredentials() ([]client.DigitaloceanCredentialListItem, error)
	CreateDigitaloceanCredential(req client.CreateDigitaloceanCredentialRequest) (*client.CreateDigitaloceanCredentialResponse, error)
	ListDigitaloceanSSHKeyCredentials() ([]client.DigitaloceanCredentialListItem, error)
	CreateDigitaloceanSSHKeyCredential(req client.CreateSSHKeyCredentialRequest) (*client.CreateSSHKeyCredentialResponse, error)

	StopScalewayCluster(clusterID string) (*client.ProviderStopClusterResponse, error)
	StartScalewayCluster(clusterID, scope string) (*client.ProviderStartClusterResult, error)
	CreateProxmoxCluster(request client.CreateProxmoxClusterRequest) (*client.CreateProxmoxClusterResponse, error)
	DeprovisionProxmoxCluster(clusterID string) (*client.ProviderDeprovisionClusterResponse, error)
	StopProxmoxCluster(clusterID string) (*client.ProviderStopClusterResponse, error)
	StartProxmoxCluster(clusterID, scope string) (*client.ProviderStartClusterResult, error)
	GetProxmoxWorkerCount(clusterID string) (*client.WorkerCountResult, error)
	ScaleProxmoxWorkers(clusterID string, workerCount int) (*client.ScaleWorkersResult, error)
	GetProxmoxK8sVersion(clusterID string) (*client.K8sVersionInfo, error)
	UpgradeProxmoxK8sVersion(clusterID, targetVersion string, force bool) (*client.UpgradeK8sVersionResult, error)
	ListProxmoxNodeGroups(clusterID string) (*client.NodeGroupListResult, error)
	AddProxmoxNodeGroup(ctx context.Context, clusterID string, request client.AddNodeGroupRequest, wait bool) (*client.AddNodeGroupResult, bool, error)
	ScaleProxmoxNodeGroup(ctx context.Context, clusterID, groupName string, count int, wait bool) (*client.ScaleNodeGroupResult, bool, error)
	UpdateProxmoxNodeGroupInstanceType(ctx context.Context, clusterID, groupName, instanceType string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	DeleteProxmoxNodeGroup(ctx context.Context, clusterID, groupName string, wait bool) (*client.DeleteNodeGroupResult, bool, error)
	GetProxmoxNodeGroupAutoscaling(clusterID, groupName string) (*client.NodeGroupAutoscalingResult, error)
	UpdateProxmoxNodeGroupAutoscaling(ctx context.Context, clusterID, groupName string, request client.NodeGroupAutoscalingRequest, wait bool) (*client.NodeGroupAutoscalingResult, bool, error)
	UpdateProxmoxNodeGroupLabels(ctx context.Context, clusterID, groupName string, labels map[string]string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	UpdateProxmoxNodeGroupTaints(ctx context.Context, clusterID, groupName string, taints []client.NodeTaint, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	GetProxmoxControlPlane(clusterID string) (*client.ControlPlaneInfo, error)
	ChangeProxmoxControlPlaneCount(clusterID string, count int) (*client.ChangeControlPlaneCountResult, error)
	ChangeProxmoxControlPlaneInstanceType(clusterID, instanceType string) (*client.ChangeControlPlaneInstanceTypeResult, error)
	ListProxmoxClusterNodes(clusterID string) (*client.NodeListResult, error)
	GetProxmoxClusterNode(clusterID, nodeID string) (*client.NodeDetail, error)
	GetProxmoxClusterSSHKeys(clusterID string) (*client.ClusterSSHKeysResult, error)
	UpdateProxmoxClusterSSHKeys(clusterID string, sshKeyCredentialIDs []string) (*client.UpdateClusterSSHKeysResult, error)
	ResyncProxmoxClusterSSHKeys(clusterID string) (*client.ResyncSSHKeysResult, error)
	ListProxmoxNodes(credentialID string) ([]client.ProxmoxNode, error)
	ListProxmoxStorages(credentialID, node string) ([]client.ProxmoxStorage, error)
	ListProxmoxBridges(credentialID, node string) ([]client.ProxmoxBridge, error)
	ListProxmoxTemplates(credentialID, node string) ([]client.ProxmoxTemplate, error)
	ListProxmoxSizes() ([]client.ProxmoxSize, error)

	ListProxmoxCredentials() ([]client.ProxmoxCredentialListItem, error)
	CreateProxmoxCredential(request client.CreateProxmoxCredentialRequest) (*client.CreateProxmoxCredentialResponse, error)
	ListProxmoxSSHKeyCredentials() ([]client.ProxmoxCredentialListItem, error)
	CreateProxmoxSSHKeyCredential(request client.CreateSSHKeyCredentialRequest) (*client.CreateSSHKeyCredentialResponse, error)

	CreateMorpheusCluster(request client.CreateMorpheusClusterRequest) (*client.CreateMorpheusClusterResponse, error)
	DeprovisionMorpheusCluster(clusterID string) (*client.ProviderDeprovisionClusterResponse, error)
	StopMorpheusCluster(clusterID string) (*client.ProviderStopClusterResponse, error)
	StartMorpheusCluster(clusterID, scope string) (*client.ProviderStartClusterResult, error)
	GetMorpheusWorkerCount(clusterID string) (*client.WorkerCountResult, error)
	ScaleMorpheusWorkers(clusterID string, workerCount int) (*client.ScaleWorkersResult, error)
	GetMorpheusK8sVersion(clusterID string) (*client.K8sVersionInfo, error)
	UpgradeMorpheusK8sVersion(clusterID, targetVersion string, force bool) (*client.UpgradeK8sVersionResult, error)
	ListMorpheusNodeGroups(clusterID string) (*client.NodeGroupListResult, error)
	AddMorpheusNodeGroup(ctx context.Context, clusterID string, request client.AddNodeGroupRequest, wait bool) (*client.AddNodeGroupResult, bool, error)
	ScaleMorpheusNodeGroup(ctx context.Context, clusterID, groupName string, count int, wait bool) (*client.ScaleNodeGroupResult, bool, error)
	UpdateMorpheusNodeGroupInstanceType(ctx context.Context, clusterID, groupName, instanceType string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	DeleteMorpheusNodeGroup(ctx context.Context, clusterID, groupName string, wait bool) (*client.DeleteNodeGroupResult, bool, error)
	GetMorpheusNodeGroupAutoscaling(clusterID, groupName string) (*client.NodeGroupAutoscalingResult, error)
	UpdateMorpheusNodeGroupAutoscaling(ctx context.Context, clusterID, groupName string, request client.NodeGroupAutoscalingRequest, wait bool) (*client.NodeGroupAutoscalingResult, bool, error)
	UpdateMorpheusNodeGroupLabels(ctx context.Context, clusterID, groupName string, labels map[string]string, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	UpdateMorpheusNodeGroupTaints(ctx context.Context, clusterID, groupName string, taints []client.NodeTaint, wait bool) (*client.UpdateNodeGroupResult, bool, error)
	GetMorpheusControlPlane(clusterID string) (*client.ControlPlaneInfo, error)
	ChangeMorpheusControlPlaneCount(clusterID string, count int) (*client.ChangeControlPlaneCountResult, error)
	ChangeMorpheusControlPlaneInstanceType(clusterID, instanceType string) (*client.ChangeControlPlaneInstanceTypeResult, error)
	ListMorpheusClusterNodes(clusterID string) (*client.NodeListResult, error)
	GetMorpheusClusterNode(clusterID, nodeID string) (*client.NodeDetail, error)
	GetMorpheusClusterSSHKeys(clusterID string) (*client.ClusterSSHKeysResult, error)
	UpdateMorpheusClusterSSHKeys(clusterID string, sshKeyCredentialIDs []string) (*client.UpdateClusterSSHKeysResult, error)
	ResyncMorpheusClusterSSHKeys(clusterID string) (*client.ResyncSSHKeysResult, error)
	ListMorpheusGroups(credentialID string) ([]client.MorpheusGroup, error)
	ListMorpheusClouds(credentialID string) ([]client.MorpheusCloud, error)
	ListMorpheusPlans(credentialID string) ([]client.MorpheusPlan, error)
	ListMorpheusLayouts(credentialID string) ([]client.MorpheusLayout, error)
	ListMorpheusNetworks(credentialID string) ([]client.MorpheusNetwork, error)

	ListMorpheusCredentials() ([]client.MorpheusCredentialListItem, error)
	CreateMorpheusCredential(request client.CreateMorpheusCredentialRequest) (*client.CreateMorpheusCredentialResponse, error)
	ListMorpheusSSHKeyCredentials() ([]client.MorpheusCredentialListItem, error)
	CreateMorpheusSSHKeyCredential(request client.CreateSSHKeyCredentialRequest) (*client.CreateSSHKeyCredentialResponse, error)

	CreateManagedCluster(provider client.ManagedK8sProvider, request client.CreateManagedClusterRequest) (*client.CreateManagedClusterResponse, error)
	DeprovisionManagedCluster(provider client.ManagedK8sProvider, clusterID string, force bool) (*client.DeprovisionManagedClusterResponse, error)
	AddManagedNodePool(provider client.ManagedK8sProvider, clusterID string, request client.AddManagedNodePoolRequest) (*client.AddManagedNodePoolResponse, error)
	ScaleManagedNodePool(provider client.ManagedK8sProvider, clusterID, nodePoolName string, count int) (*client.ScaleManagedNodePoolResponse, error)
	DeleteManagedNodePool(provider client.ManagedK8sProvider, clusterID, nodePoolName string) (*client.DeleteManagedNodePoolResponse, error)
	UpdateManagedNodePool(provider client.ManagedK8sProvider, clusterID, nodePoolName string, request client.UpdateManagedNodePoolRequest) (*client.UpdateManagedNodePoolResponse, error)
	UpgradeManagedK8sVersion(provider client.ManagedK8sProvider, clusterID, version string) (*client.UpgradeManagedK8sVersionResponse, error)
	StopManagedCluster(provider client.ManagedK8sProvider, clusterID string) (*client.ManagedClusterLifecycleResponse, error)
	StartManagedCluster(provider client.ManagedK8sProvider, clusterID string) (*client.ManagedClusterLifecycleResponse, error)
}
