apiVersion: v1
kind: ImportCluster
metadata:
  name: local-import-cluster
  description: Importing my Kubernetes cluster
spec:
  git_repository:
    provider: github
    credential_name: User-Myothas
    repository: Myothas/test-github-repo
    branch: main
  stacks:
    - name: test
      description: Stack for testing
      addons:
        - name: test-addon
          chart_name: cert-manager
          chart_version: v1.14.4
          repository_url: https://charts.jetstack.io
          namespace: cert-manager
          configuration_type: standalone
      manifests:
        - name: test-manifest
          from_file: fluent-bit-namespace.yaml
          parents:
            - name: "test-addon"
              kind: "addon"
